blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/ahusan/cleaninstall-node/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/ahusan/cleaninstall-node#readme
    about: Read the documentation
